spring.application.name=stock-control-api
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/stock_control
spring.datasource.username=stock_control
spring.datasource.password=stock_control

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true